Add the compile implementation with supporting scripts

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,6 +1,41 @@
 #!/usr/bin/env bash
 # bin/compile <build-dir> <cache-dir> <env-dir>
 
+# fail fast
+set -e
+
 BUILD_DIR=$1
 CACHE_DIR=$2
 ENV_DIR=$3
+
+CIRCLECI_TOKEN=`cat $ENV_DIR/CIRCLECI_TOKEN`
+CIRCLECI_PROJECT=`cat $ENV_DIR/CIRCLECI_PROJECT`
+CIRCLECI_ARTIFACT=`cat $ENV_DIR/CIRCLECI_ARTIFACT`
+JSON_HEADER='Accept:application/json'
+COMMIT=`git log --pretty=oneline -1 | cut -d' ' -f1`
+
+CIRCLECI_BASE_URL='https://circleci.com/api/v1/project'
+CIRCLECI_PROJECT_URL="$CIRCLECI_BASE_URL/$CIRCLECI_PROJECT"
+BRANCH=`git rev-parse --abbrev-ref HEAD`
+CIRCLECI_BUILDS_URL="$CIRCLECI_PROJECT_URL/tree/$BRANCH?circle-token=$CIRCLECI_TOKEN&limit=5"
+
+BUILDS_OUTPUT='builds.json'
+
+curl --header $JSON_HEADER -o $BUILDS_OUTPUT $CIRCLECI_BUILDS_URL
+
+CIRCLECI_BUILD_NUMBER=`bin/get_build $COMMIT $BUILDS_OUTPUT`
+
+CIRCLECI_ARTIFACTS_URL="$CIRCLECI_PROJECT_URL/$CIRCLECI_BUILD_NUMBER/artifacts?circle-token=$CIRCLECI_TOKEN"
+
+ARTIFACTS_OUTPUT='artifacts.json'
+
+curl --header $JSON_HEADER -o $ARTIFACTS_OUTPUT $CIRCLECI_ARTIFACTS_URL
+
+CIRCLECI_ARTIFACT_URL=`bin/get_artifact $CIRCLECI_ARTIFACT $ARTIFACTS_OUTPUT`
+
+curl -ssl3 -O $CIRCLECI_ARTIFACT_URL
+
+if [ -e $CIRCLECI_ARTIFACT ]
+then
+  tar -xzf $CIRCLECI_ARTIFACT
+fi
